import {IEmployee} from "../interfaces/company.interfaces";


export const COMPANY_EMPLOYEE: IEmployee[] = [
    {
        id: 'USR-SF-001',
        firstName: 'John',
        lastName: 'Doe',
        age: 30,
        email: 'john.doe@example.com',
        position: 'Software Engineer',
        departament: 'Development',
        employWorkDate: '2020-01-15',
        relatedUsers: [],
        address: {
            city: 'San Francisco',
            street: 'Main St',
            zipCode: '94101',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-NY-002',
        firstName: 'Jane',
        lastName: 'Smith',
        age: 28,
        email: 'jane.smith@example.com',
        position: 'UX Designer',
        departament: 'Design',
        employWorkDate: '2021-03-01',
        relatedUsers: [],
        address: {
            city: 'New York',
            street: 'Broadway',
            zipCode: '10001',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-CH-003',
        firstName: 'Michael',
        lastName: 'Johnson',
        age: 35,
        email: 'michael.j@example.com',
        position: 'Project Manager',
        departament: 'Management',
        employWorkDate: '2019-07-20',
        relatedUsers: [],
        address: {
            city: 'Chicago',
            street: 'Oak Ave',
            zipCode: '60601',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-SE-004',
        firstName: 'Emily',
        lastName: 'Brown',
        age: 25,
        email: 'emily.b@example.com',
        position: 'Frontend Developer',
        departament: 'Development',
        employWorkDate: '2022-02-10',
        relatedUsers: [],
        address: {
            city: 'Seattle',
            street: 'Pine St',
            zipCode: '98101',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-AU-005',
        firstName: 'David',
        lastName: 'Davis',
        age: 32,
        email: 'david.d@example.com',
        position: 'Backend Developer',
        departament: 'Development',
        employWorkDate: '2020-09-01',
        relatedUsers: [],
        address: {
            city: 'Austin',
            street: 'Elm St',
            zipCode: '78701',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-BO-006',
        firstName: 'Sarah',
        lastName: 'Miller',
        age: 29,
        email: 'sarah.m@example.com',
        position: 'QA Engineer',
        departament: 'Quality Assurance',
        employWorkDate: '2021-06-15',
        relatedUsers: [],
        address: {
            city: 'Boston',
            street: 'Beacon St',
            zipCode: '02108',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-DE-007',
        firstName: 'Chris',
        lastName: 'Wilson',
        age: 31,
        email: 'chris.w@example.com',
        position: 'DevOps Engineer',
        departament: 'Operations',
        employWorkDate: '2019-11-05',
        relatedUsers: [],
        address: {
            city: 'Denver',
            street: 'Cherry Creek',
            zipCode: '80202',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-PO-008',
        firstName: 'Olivia',
        lastName: 'Moore',
        age: 27,
        email: 'olivia.m@example.com',
        position: 'Data Analyst',
        departament: 'Data Science',
        employWorkDate: '2022-04-01',
        relatedUsers: [],
        address: {
            city: 'Portland',
            street: 'Hawthorne Blvd',
            zipCode: '97201',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-MI-009',
        firstName: 'Daniel',
        lastName: 'Taylor',
        age: 33,
        email: 'daniel.t@example.com',
        position: 'Product Owner',
        departament: 'Product Management',
        employWorkDate: '2018-08-01',
        relatedUsers: [],
        address: {
            city: 'Miami',
            street: 'Ocean Dr',
            zipCode: '33139',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-DA-010',
        firstName: 'Sophia',
        lastName: 'Anderson',
        age: 26,
        email: 'sophia.a@example.com',
        position: 'Technical Writer',
        departament: 'Documentation',
        employWorkDate: '2023-01-01',
        relatedUsers: [],
        address: {
            city: 'Dallas',
            street: 'Main St',
            zipCode: '75201',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-SF-011',
        firstName: 'Grace',
        lastName: 'White',
        age: 31,
        email: 'grace.w@example.com',
        position: 'Fullstack Developer',
        departament: 'Development',
        employWorkDate: '2021-05-20',
        relatedUsers: [],
        address: {
            city: 'San Francisco',
            street: 'Market St',
            zipCode: '94102',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-NY-012',
        firstName: 'Leo',
        lastName: 'Clark',
        age: 29,
        email: 'leo.c@example.com',
        position: 'UI Designer',
        departament: 'Design',
        employWorkDate: '2022-08-10',
        relatedUsers: [],
        address: {
            city: 'New York',
            street: 'Wall St',
            zipCode: '10005',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-CH-013',
        firstName: 'Nora',
        lastName: 'Lewis',
        age: 34,
        email: 'nora.l@example.com',
        position: 'Scrum Master',
        departament: 'Management',
        employWorkDate: '2020-03-01',
        relatedUsers: [],
        address: {
            city: 'Chicago',
            street: 'Michigan Ave',
            zipCode: '60611',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-LA-014',
        firstName: 'Liam',
        lastName: 'Young',
        age: 27,
        email: 'liam.y@example.com',
        position: 'Backend Developer',
        departament: 'Development',
        employWorkDate: '2023-04-15',
        relatedUsers: [],
        address: {
            city: 'Los Angeles',
            street: 'Sunset Blvd',
            zipCode: '90028',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-PH-015',
        firstName: 'Zoe',
        lastName: 'King',
        age: 30,
        email: 'zoe.k@example.com',
        position: 'Manual QA',
        departament: 'Quality Assurance',
        employWorkDate: '2022-01-01',
        relatedUsers: [],
        address: {
            city: 'Philadelphia',
            street: 'Broad St',
            zipCode: '19107',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-DE-016',
        firstName: 'Ryan',
        lastName: 'Green',
        age: 36,
        email: 'ryan.g@example.com',
        position: 'Network Engineer',
        departament: 'Operations',
        employWorkDate: '2018-10-01',
        relatedUsers: [],
        address: {
            city: 'Denver',
            street: '16th Street Mall',
            zipCode: '80202',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-PO-017',
        firstName: 'Mia',
        lastName: 'Hall',
        age: 26,
        email: 'mia.h@example.com',
        position: 'Business Intelligence Analyst',
        departament: 'Data Science',
        employWorkDate: '2023-02-01',
        relatedUsers: [],
        address: {
            city: 'Portland',
            street: 'Burnside St',
            zipCode: '97209',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-OR-018',
        firstName: 'Jack',
        lastName: 'Adams',
        age: 33,
        email: 'jack.a@example.com',
        position: 'Senior Product Manager',
        departament: 'Product Management',
        employWorkDate: '2019-09-01',
        relatedUsers: [],
        address: {
            city: 'Orlando',
            street: 'International Dr',
            zipCode: '32819',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-DA-019',
        firstName: 'Ella',
        lastName: 'Baker',
        age: 25,
        email: 'ella.b@example.com',
        position: 'Content Creator',
        departament: 'Documentation',
        employWorkDate: '2024-01-10',
        relatedUsers: [],
        address: {
            city: 'Dallas',
            street: 'Elm St',
            zipCode: '75202',
        },
        profilePicture: '',
        isChecked: false,
    },
    {
        id: 'USR-SF-020',
        firstName: 'Noah',
        lastName: 'Nelson',
        age: 30,
        email: 'noah.n@example.com',
        position: 'Software Engineer',
        departament: 'Development',
        employWorkDate: '2021-07-01',
        relatedUsers: [],
        address: {
            city: 'San Francisco',
            street: 'California St',
            zipCode: '94104',
        },
        profilePicture: '',
        isChecked: false,
    },
];
